# Generated by Django 5.1.5 on 2025-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, help_text='Unique ticket code (e.g., QR code identifier)', max_length=20),
        ),
    ]
